# Generated by Django 4.0.4 on 2022-05-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.task')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Ресторан', 'verbose_name_plural': 'Рестораны'},
        ),
    ]
