# Generated by Django 4.0.4 on 2022-05-25 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время написания'),
        ),
    ]
