# Generated by Django 4.0.4 on 2022-05-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_services'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='services',
            table='services',
        ),
    ]
