# Generated by Django 4.0.4 on 2022-05-27 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='val',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка пользователя'),
        ),
    ]
